### PR TITLE
add additional info to testTask (#9)

### LINKED ISSUE #9: Make `Debug.testTask` more "faithful"
To be able to better judge how things will turn out in Autotool, I assume it would make sense to do the following two things.

# 1.

In https://github.com/fmidue/output-monad/blob/d469ed0b22df718dde4d4d718a7f6fd54cfe2a0d/output-monad/src/Control/Monad/Output/Debug.hs#L43-L44 additionally print out how `value` would look pretty-printed. That is, how it turns out with the `Pretty` instead of the `Show` instance.

That should help identify issues in situations like this: https://github.com/fmidue/logic-tasks/issues/81#issuecomment-1917269129 

# 2.

In https://github.com/fmidue/output-monad/blob/d469ed0b22df718dde4d4d718a7f6fd54cfe2a0d/output-monad/src/Control/Monad/Output/Debug.hs#L46-L49 whenever `partialRes == Nothing`, print out a reminder that the stuff after `---- Complete ----` would not actually be printed in Autotool.

### PR DESCRIPTION
**Pull request by marcellussiegburg**
- close #9

### CODE REVIEW

**Comment by marcellussiegburg** [comment]
@jvoigtlaender It addresses the first point of #9 by making it optional to pretty print the result (and requiring to provide such function, thus avoiding an additional constraint).

**Comment by jvoigtlaender** [comment]
> and requiring to provide such function

It requires a function `a -> String`. But at least the use case where the problem appeared (https://github.com/fmidue/logic-tasks/issues/81#issuecomment-1917269129) would immediately have had an `a -> Doc` at hand. That is, the natural thing there would have been to call `testTask (Just pretty) ...`.

Would changing the argument to `Maybe (a -> Doc)` introduce a problematic dependency? Or what would one write in `testTask (Just ...)` to satisfy the `-> String`?

**Comment by marcellussiegburg** [comment]
I guess it is okay to introduce the dependency. It limits the pretty function to this `Doc` type, but I guess that is fine (because if it does, it should use it anyway for Autotool tasks).

**Comment by jvoigtlaender** [comment]
Actually not sure now what "this `Doc`" type is. In `logic-tasks`, `Doc` comes from Daan's library, but that's not the `Doc` inside Autotool, right?

So maybe using `Doc` here is indeed too specific.

**Comment by marcellussiegburg** [comment]
> Or what would one write in `testTask (Just ...)` to satisfy the `-> String`?

`...` could be `Just (T.pack . displayTStrict . pretty)`

**Comment by jvoigtlaender** [comment]
Oh, why `pack`? Wouldn't that give `Text` instead of `String`?

**Comment by marcellussiegburg** [comment]
Oh, right. Sorry, this should be `T.unpack`

**Comment by jvoigtlaender** [comment]
Hmm, `Just (show . pretty)` wouldn't work? The code with `displayStrict` etc. seems unwieldy and in particular is something one probably wouldn't remember in a debugging session.

**Comment by marcellussiegburg** [comment]
This latest attempt provides liberty onto how to pretty print. In the aforementioned case one would use `Just AutoLeijen`. [But would also be allowed to write `Just (Manual $ T.unpack . PP.displayTStrict . PP.renderPretty 0.4 80 . PP.pretty)`; or better in other cases, if a not yet supported Pretty-Library is used. `Leijen` might also be hard to remember, but should appear in the import List!]

**Review by jvoigtlaender — APPROVED** [review]

**Pull request merged**
